### ISSUE TITLE
Export image wrong size when not enabled

### ISSUE THREAD

**Issue by DrewLX** [Alteka/Kards#28]
Exporting an image whilst the card isn't enabled causes the image to be of a random size.

**Comment by DrewLX** [comment]
@canoemoose Are we happy this is resolved in latest dev branch?

**Comment by canoemoose** [comment]
This is still broken in a built and installed version of the dev branch at 6c3a952

**Comment by DrewLX** [comment]
With what settings, I can't replicate?

**Comment by DrewLX** [comment]
This is fixed
